### ISSUE TITLE
error fetching checks 

### ISSUE THREAD

**Issue by Arjun31415** [ldelossa/gh.nvim#2] opened 2022-05-10 04:54 UTC
Hangs on `Fetching checks` and then notifies with `failed to fetch remote branch`

### Neovim version - 
v0.8.0-dev+160-gdbdd58e54

### Config-
```lua
 use({
            'ldelossa/gh.nvim',
            event = 'InsertEnter',
            requires = 'ldelossa/litee.nvim',
            config = function()
                require('litee.lib').setup()
                require('litee.gh').setup()
            end
        })
```

### Expected Outcome -
The remote branch should have been fetched and the PRs to be seen

**Comment by ldelossa** [comment] 2022-05-10 11:48
Can you provide more info? Its most likely not hanging on "fetching checks", thats just the final API call. 

gh.nvim is attempting to do git operations at that point, it wants to add the remote of the repo locally and then fetch the pull. Do you have permissions to do that?

**Comment by Arjun31415** [comment] 2022-05-10 16:12
Yes, it does have permissions to do as far as I know 
what would be the equivalent git commands, maybe I can try to run that to see if I run into an error

**Comment by ldelossa** [comment] 2022-05-11 12:49
https://github.com/ldelossa/gh.nvim/blob/8ed9bec691000f78dbd162baf02e1beb43f487e0/lua/litee/gh/pr/handlers.lua#L54-L70 - these are the lines which are giving you a problem. 

gh.nvim is pretty new, so unfortunately logging is not great yet. But for your repo the `gitcli.fetch` seems to be failing. This equates to a this function call: https://github.com/ldelossa/gh.nvim/blob/8ed9bec691000f78dbd162baf02e1beb43f487e0/lua/litee/gh/gitcli/init.lua#L34-L41

You'll need to log out the remote and branch name in your particular case which is causing the issue. Also, is your repo public ? If so I can just try to reproduce on my end.

**Comment by Arjun31415** [comment] 2022-05-11 14:03
After going through the remotes and branches I found that another remote `litee-gh_<username>/<repository-name>` was created. And this one has an issue
```
The authenticity of host 'github.com (13.234.210.38)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])?
```

**Comment by ldelossa** [comment] 2022-05-11 14:03
Yup, we try to add the remote ourselves so we can pull the code. Did we create the remote incorrectly?

**Comment by Arjun31415** [comment] 2022-05-11 14:05
The solutions say that I need to add SSH Keys. I am not sure if I want to set that up. Is there a workaround

**Comment by ldelossa** [comment] 2022-05-11 15:49
@Arjun31415 so I determined that is just my git configuration setting, I swap all http remotes to SSH. 

We can theoretically avoid ssh all together and use the https remote, the user will deal with pushing/pull on their own as gh.nvim does not involve itself with that. 

Are you able to try this branch? And add the necessary config value? https://github.com/ldelossa/gh.nvim/pull/3

**Comment by ldelossa** [comment] 2022-05-11 16:05
Up to you, if you prefer no to use SSH keys, this should be an option for you. If not, its okay I'll still merge as some ppl may want to not use ssh keys.

**Comment by ldelossa** [comment] 2022-05-11 16:16
cool, will merge now.

**Comment by Arjun31415** [comment] 2022-05-11 16:16
Happy to help

**Comment by ldelossa** [comment] 2022-05-11 16:17
Closing issue, feel free to re-open if any other problems.

**Closed by ldelossa** 2022-05-11 16:17 UTC
